### ISSUE TITLE
existing *.lock files prevents "npx yarn install"

### ISSUE THREAD

**Issue by solidrevolution** [thoughtram/angular-master-class-starter#7]
Hello,

Currently existing lock files causes the following error when "npx yarn install" is executed 

`error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".`

deleting the files yarn.lock and package-lock.json solves this

**Comment by PascalPrecht** [comment]
Hey @solidrevolution !

Thank you for reporting this. It looked like the `master` branch of the starter kit didn't get updated properly. I've just updated it. Can you reset your clone to it and try again please?

**Comment by solidrevolution** [comment]
we tried on another colleague's machine it is working now.

super thanks!

**Comment by PascalPrecht** [comment]
Thanks! Closing this
